project:
  type: website
  output-dir: _site


website:
  title: "BlogDen"
  page-footer: 
    left: |
      BlogDen
    center:
      - text: "Tentang"
        href: about.qmd
    right: 
      - icon: twitter
      - icon: instagram
      - icon: github
  navbar:
    background: light
    title: false
    collapse-below: lg
    left:
      - text: "Beranda"
        href: index.qmd
      - text: "Python"
        href: docs/python-programming/index.qmd
      - text: "Kalkulus"
        href: docs/kalkulus/index.qmd
      - text: "Fisika Dasar"
        href: docs/fisika-dasar/index.qmd
      # - text: "Blog"
      #   href: docs/blog/index.qmd
      - text: "Tentang Saya"
        href: about.qmd
    right:
      - icon: github
        href: https://github.com/zooxs
      - icon: twitter
        href: https://twitter.com
      - icon: instagram
        href: https://instagram.com/atensiden
      
format:
  html:
    theme: cosmos
    include-before-body: docs/share-on-button.html
    css: styles.css

lang: id
language: bahasa.yml